stages:
  - build
  - deploy

variables:
  LTS_VERSION: "2204"

before_script:
  - "$LATEST_TAG=$(git describe --abbrev=0)"
  - '$BUILD_NAME="UBUNTULTS$LTS_VERSION-$LATEST_TAG-$(Get-Date -Format yyMMdd)-$CI_PIPELINE_IID"'
  - '$env:PKR_VAR_vm_notes="$BUILD_NAME by Stefan Zimmermann"'

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

packer:
  stage: build
  before_script:
    - 'Remove-Item -Path .\build\ -Recurse -Force; $exit_code = $?'
  script:
    - "packer init -upgrade ."
    - "packer build -timestamp-ui -var-file ubuntults$LTS_VERSION.pkrvars.hcl -force ."
    - 'tar -C build/ -cvf build/$($BUILD_NAME).ova *.mf *.ovf *.vmdk'
  tags:
    - packer
    - tar
  cache:
    paths:
      - packer_cache/
  artifacts:
    paths:
      - "build/*.ova"
    expire_in: 1 hours
  rules:
    - when: on_success

copytosmb:
  stage: deploy
  script:
    - 'Move-Item -Path .\build\*.ova -Destination $SMB_PATH\$BUILD_NAME.ova'
  tags:
    - windows
  rules:
    - if: $SMB_PATH
      when: on_success
    - when: never