stages:
  - build
  - deploy

before_script:
  - "$LATEST_TAG=$(git describe --abbrev=0)"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

packer:
  stage: build
  before_script:
    - 'Remove-Item -Path .\output-vmware-iso\ -Recurse -Force; $exit_code = $?'
  script:
    - "packer build ubuntults.json"
  tags:
    - packer
    - windows
    - ovftool
  cache:
    paths:
      - packer_cache/
  artifacts:
    paths:
      - "output-vmware-iso/"
    expire_in: 1 hours
  rules:
    - when: always

copytosmb:
  stage: deploy
  script:
    - 'Move-Item -Path .\output-vmware-iso\*.ova -Destination
      $SMB_PATH\UBUNTULTS-$LATEST_TAG-$(Get-Date -Format
      "yyMMdd")-$CI_PIPELINE_IID.ova'
  tags:
    - packer
    - windows
    - ovftool
  rules:
    - if: $SMB_PATH
      when: on_success
    - when: never
